# Lecture 4-2

# More NumPy

## Week 4 Wednesday

## Miles Chen, PhD

Based on Python Data Science Handbook by Jake VanderPlas

In [1]:
import numpy as np

## Concatenating Arrays

In [2]:
x = np.arange(4)
y = np.arange(100, 104)
print(x)
print(y)

[0 1 2 3]
[100 101 102 103]


In [3]:
np.concatenate([x,y])

array([  0,   1,   2,   3, 100, 101, 102, 103])

`np.concatenate` has an argument for axis. The axes are 0-indexed.

In [4]:
np.concatenate([x,y], axis = 0)

array([  0,   1,   2,   3, 100, 101, 102, 103])

Let's try to concatenate in the other direction. We specify axis = 1

In [5]:
np.concatenate([x,y], axis = 1) # throws an error

AxisError: axis 1 is out of bounds for array of dimension 1

In [6]:
x.shape # you can't use axis with index 1, because axis index 1 does not exist

(4,)

In [7]:
np.vstack([x,y])   # vstack will vertically stack unidimensional arrays

array([[  0,   1,   2,   3],
       [100, 101, 102, 103]])

In [8]:
x.reshape(1,4)

array([[0, 1, 2, 3]])

In [9]:
y.reshape(1,4)

array([[100, 101, 102, 103]])

In [10]:
np.concatenate([x.reshape(1,4), y.reshape(1,4)], axis = 0)

array([[  0,   1,   2,   3],
       [100, 101, 102, 103]])

note that when I concatenate along axis 0 for a 2-dimensional array, it concatenates by rows. In a 2D array, index 0 is for rows, and index 1 is for columns.

In [11]:
np.concatenate([x.reshape(1,4), y.reshape(1,4)], axis = 1)

array([[  0,   1,   2,   3, 100, 101, 102, 103]])

In [12]:
xm = np.arange(6).reshape((2,3))
ym = np.arange(100,106,1).reshape((2,3))
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [13]:
xm.shape

(2, 3)

In [14]:
ym.shape

(2, 3)

In [15]:
print(np.concatenate([xm,ym])) # default behavior concatenates on axis 0

[[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]


In [16]:
print(np.concatenate([xm,ym], axis = 0))  
# axes are reported as rows, then columns.
# concatenating along axis 0 will concatenate along rows

[[  0   1   2]
 [  3   4   5]
 [100 101 102]
 [103 104 105]]


In [17]:
print(np.concatenate([xm,ym], axis = 1))
# concatenating along axis 1 will concatenate along columns

[[  0   1   2 100 101 102]
 [  3   4   5 103 104 105]]


In [18]:
np.vstack([xm, ym])

array([[  0,   1,   2],
       [  3,   4,   5],
       [100, 101, 102],
       [103, 104, 105]])

In [19]:
np.hstack([xm, ym])

array([[  0,   1,   2, 100, 101, 102],
       [  3,   4,   5, 103, 104, 105]])

You can always use vstack and hstack for 2D arrays.

## Math Operators with numpy arrays

In [20]:
print(x)
print(y)

[0 1 2 3]
[100 101 102 103]


In [21]:
x + 5

array([5, 6, 7, 8])

In [22]:
x + y  # elementwise addition

array([100, 102, 104, 106])

In [23]:
x * y 

array([  0, 101, 204, 309])

In [24]:
np.sum(x * y)

614

np.dot(x,y)   # 0 * 100 + 1 * 101 + 2 * 102 + 3 * 103

In [25]:
x @ y # matrix multiplication

614

In [26]:
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [27]:
xm + 5

array([[ 5,  6,  7],
       [ 8,  9, 10]])

In [28]:
xm + ym  # elementwise addition

array([[100, 102, 104],
       [106, 108, 110]])

In [29]:
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [30]:
xm * ym # element-wise multiplication

array([[  0, 101, 204],
       [309, 416, 525]])

In [31]:
np.multiply(xm, ym) # element-wise multiplication

array([[  0, 101, 204],
       [309, 416, 525]])

In [32]:
print(xm)
print(ym)

[[0 1 2]
 [3 4 5]]
[[100 101 102]
 [103 104 105]]


In [33]:
np.dot(xm, ym.T)

array([[ 305,  314],
       [1214, 1250]])

In [34]:
xm.dot(ym.T)

array([[ 305,  314],
       [1214, 1250]])

In [35]:
xm @ ym.T

array([[ 305,  314],
       [1214, 1250]])

# Basic Math

In [36]:
x = np.arange(4)
print(x)

[0 1 2 3]


In [37]:
print(x + 4)

[4 5 6 7]


In [38]:
print(x - 5)

[-5 -4 -3 -2]


In [39]:
print(x * 2)

[0 2 4 6]


In [40]:
print(x / 2)

[0.  0.5 1.  1.5]


In [41]:
print(-x)

[ 0 -1 -2 -3]


In [42]:
print(x ** 2)

[0 1 4 9]


In [43]:
print(x % 2) # modulo division

[0 1 0 1]


In [44]:
print(abs(x)) # abs

[0 1 2 3]


# Trig functions
note that the functions are preceeded by np.

In [45]:
theta = np.linspace(0, np.pi, 5)
print(theta)

[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [46]:
import math
print(theta[1] / math.pi)

0.25


In [47]:
print(np.sin(theta))

[0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]


In [48]:
print(np.cos(theta))

[ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]


In [49]:
print(np.tan(theta))

[ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


# Log and Exp

In [50]:
x = np.array([1, 10, 100])
print(np.log(x))   # natural log
print(np.log10(x)) # common log

[0.         2.30258509 4.60517019]
[0. 1. 2.]


In [51]:
y = np.arange(3)
print(np.exp(y))  # e^y

[1.         2.71828183 7.3890561 ]


In [52]:
print(np.exp2(y))  # 2^y

[1. 2. 4.]


In [53]:
print(np.power(3, y)) # power ^ y

[1 3 9]


# Aggregates

you can use `sum()`

or `np.sum()`

`np.sum()` is faster than sum, but doesn't always behave the same way

In [54]:
x = np.arange(100)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [ ]:
print(sum(x))

In [55]:
print(np.sum(x))

4950


In [77]:
big_array = np.random.rand(10000)
#%timeit sum(big_array)
#%timeit np.sum(big_array)  # the np version is much faster

## min and max

In [78]:
print(min(big_array))
print(max(big_array))

7.162253241876915e-05
0.9999193115838715


In [ ]:
print(np.min(big_array))
print(np.max(big_array))

In [ ]:
%timeit min(big_array)
%timeit np.min(big_array)  # the np version is much faster

## summaries for matrices

In [79]:
np.random.seed(1)
# M = np.random.random((3, 4))
M = np.arange(12)
np.random.shuffle(M)
M = np.reshape(M, (3,4))
print(M)

[[ 2  3  4 10]
 [ 1  6  0  7]
 [11  9  8  5]]


In [ ]:
sum(M) # regular sum function

In [34]:
np.sum(M) # np.sum function

66

In [35]:
print(M)

[[ 2  3  4 10]
 [ 1  6  0  7]
 [11  9  8  5]]


In [80]:
np.sum(M, axis = 0)  # np.sum function with axis specified
# matrices have two dimensions
# 0 is rows, 1 is columns
# np.sum axis = 0, will sum over rows, so you end up getting column totals

array([14, 18, 12, 22])

In [ ]:
np.sum(M, axis = 1)

In [ ]:
np.min(M, axis = 0)

In [ ]:
print(M)

In [ ]:
np.std(M)

In [37]:
np.std(M, axis = 0)

array([4.49691252, 2.44948974, 3.26598632, 2.05480467])

In [38]:
np.mean(M, axis = 1)

array([4.75, 3.5 , 8.25])

## Summaries for higher dimensional arrays

In [39]:
np.random.seed(1)
A = np.ones(24)
np.random.shuffle(A)
A = np.reshape(A, (2, 3, 4)) # two sheets, 3 rows, 4 columns
print(A)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [84]:
B = np.array([1, 2, 3, 4, 5, 6, 9, 10, 11, 12, 13, 14])
B = np.reshape(B, (2, 2, 3))
print(B)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 9 10 11]
  [12 13 14]]]


In [87]:
np.sum(B, axis = 2)

array([[ 6, 15],
       [30, 39]])

In [41]:
np.sum(A, axis = 0) # sum across "sheets"

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [42]:
np.sum(A, axis = 1) # sum across rows

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [43]:
np.sum(A, axis = 2) # sum across columns

array([[4., 4., 4.],
       [4., 4., 4.]])

## dealing with nan
nan is the float value for something that is not a number. We often use it in the place of a missing value.
nan only exists in float type.

In [44]:
x = float("nan")  # direct creation of nan
print(x)
print(type(x))

nan
<class 'float'>


In [45]:
y = float("inf")  # y is the float representation of infinity
print(y / y)  # these calculations will yield a nan result
print(y - y)

nan
nan


In [46]:
np.sum([x, 2])

nan

In [47]:
np.nansum([x, 2])   # in R you have the option na.rm = TRUE

2.0

In [ ]:
np.nanmean

The following table provides a list of useful aggregation functions available in NumPy:

|Function Name      |   NaN-safe Version  | Description                                   |
|-------------------|---------------------|-----------------------------------------------|
| ``np.sum``        | ``np.nansum``       | Compute sum of elements                       |
| ``np.prod``       | ``np.nanprod``      | Compute product of elements                   |
| ``np.mean``       | ``np.nanmean``      | Compute mean of elements                      |
| ``np.std``        | ``np.nanstd``       | Compute standard deviation                    |
| ``np.var``        | ``np.nanvar``       | Compute variance                              |
| ``np.min``        | ``np.nanmin``       | Find minimum value                            |
| ``np.max``        | ``np.nanmax``       | Find maximum value                            |
| ``np.argmin``     | ``np.nanargmin``    | Find index of minimum value                   |
| ``np.argmax``     | ``np.nanargmax``    | Find index of maximum value                   |
| ``np.median``     | ``np.nanmedian``    | Compute median of elements                    |
| ``np.percentile`` | ``np.nanpercentile``| Compute rank-based statistics of elements     |
| ``np.any``        | N/A                 | Evaluate whether any elements are true        |
| ``np.all``        | N/A                 | Evaluate whether all elements are true        |

## Broadcasting

This is a similar concept to recyling values in R, but only works when the dimensions are compatible

In [48]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)

[5 7 9]


In [49]:
c = np.array([7,8])
print(a + c)  # doesn't work

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [52]:
print(a)

[1 2 3]


In [50]:
e = np.ones([3,3])
print(e)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [51]:
print(e + a)  # the array a gets 'broadcast' across all three rows

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [53]:
print(a.reshape([3,1]))  # we reshape a to be a 3x1 array

[[1]
 [2]
 [3]]


In [54]:
print(e + a.reshape([3,1])) # the reshaped array is broadcast across columns

[[2. 2. 2.]
 [3. 3. 3.]
 [4. 4. 4.]]


In [57]:
d = np.vstack([a,b])  # we stack the arrays a and b vertically
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
a

In [ ]:
print(d + a)  # a is broadcast across row

In [55]:
print(c)

[7 8]


In [58]:
print(d)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(d + c)  # c does not have compatible dimensions

In [59]:
print(d + c.reshape([2,1]))  # after we reshape c to be a column, we can broadcast it

[[ 8  9 10]
 [12 13 14]]


In [ ]:
e = np.arange(10).reshape((10, 1))
f = np.arange(11)
print(e)
print(f)

In [ ]:
print(e + f)  ## e and f are broadcast into compatible matrices and then added

In [ ]:
print(e * f)  ## e and f are broadcast into compatible matrices and then multiplied element-wise

In [ ]:
print(d)

In [ ]:
d.reshape((1,6)) + d.reshape((6,1))

In [60]:
c = np.array([7, 8]) 

d = np.array([[1, 2, 3], [4, 5, 6]]) 

print(d + c.reshape([2, 1]))

[[ 8  9 10]
 [12 13 14]]


# Boolean Operators in NumPy

In [61]:
x = np.arange(6)
print(x)

[0 1 2 3 4 5]


In [ ]:
print(x < 3)

In [ ]:
print(x >= 3)

In [ ]:
print(x == 3)

In [ ]:
# the results can then be used to subset
print(x[x >= 3])

In [ ]:
np.sum(x >= 3) # True = 1, False = 0, so sum counts how many are true

In [ ]:
np.mean(x >= 3)  # finds the proportion that is True

In [ ]:
print(~(x == 3)) # use the tilde for negation of boolean values

In [65]:
print(~x == 3) # be careful if you leave off parenthesis

[False False False False False False]


In [64]:
~x

array([-1, -2, -3, -4, -5, -6], dtype=int32)

In [63]:
x

array([0, 1, 2, 3, 4, 5])

### Working with matrices

In [66]:
y = np.arange(12).reshape([3,4])
print(y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
print(y >= 6)

In [ ]:
np.sum(y >= 6)

In [67]:
np.sum(y >= 6, axis = 0)  # you can perform sums and other aggregate functions axis-wise on the boolean matrix

array([1, 1, 2, 2])

In [ ]:
np.sum(y >= 6, axis = 1)

## Bitwise (element-wise) Boolean operators

In [ ]:
a = np.array([True, True, False, False])
b = np.array([True, False, True, False])
print(a)
print(b)

In [ ]:
print(a & b) # bitwise and

In [ ]:
print(a | b) # bitwise or

In [ ]:
print(a ^ b) # bitwise xor (exclusive or)

In [ ]:
print(~a)  # bitwise not

In [ ]:
np.any(a)

In [ ]:
np.all(a)

# fancy indexing
Regular lists in python do not support fancy indexing, but NumPy does!

In [ ]:
np.random.seed(1)
x = np.random.randint(100, size = 10)
print(x)

In [ ]:
index = [0, 1, 5]
print(x[index])

In [ ]:
a = [1, 4, 7]
b = [2, 3, 8]
ind = np.vstack([a,b])
print(ind)

In [ ]:
print(x[ind])

In [ ]:
X = np.arange(12).reshape((3, 4))
print(X)

In [ ]:
row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
X[row, col]

- `np.sort()`
- `np.argsort()` gives the indexes of the values to have the proper sorting

In [68]:
np.random.seed(2)
x = np.arange(5)
np.random.shuffle(x)
print(x)

[2 4 1 3 0]


In [ ]:
x.sort() # sorts x in place
print(x)

In [91]:
y = np.array([5, 2, 1, 4])
print(y)
print(y.argsort())

[5 2 1 4]
[2 1 3 0]


In [92]:
y.sort()
print(y)

[1 2 4 5]


In [ ]:
d = y.argsort()
y[d]

## Sorting along rows or columns

A useful feature of NumPy's sorting algorithms is the ability to sort along specific rows or columns of a multidimensional array using the axis argument. For example:

In [94]:
np.random.seed(1)
X = np.random.randint(0, 10, (4, 6))
print(X)

[[5 8 9 5 0 0]
 [1 7 6 9 2 4]
 [5 2 4 2 4 7]
 [7 9 1 7 0 6]]


In [95]:
# sort each column of X
# np.sort returns a copy of X after sorted. It does not modify X
np.sort(X, axis=0)

array([[1, 2, 1, 2, 0, 0],
       [5, 7, 4, 5, 0, 4],
       [5, 8, 6, 7, 2, 6],
       [7, 9, 9, 9, 4, 7]])

In [96]:
# sort each row of X
np.sort(X, axis=1)

array([[0, 0, 5, 5, 8, 9],
       [1, 2, 4, 6, 7, 9],
       [2, 2, 4, 4, 5, 7],
       [0, 1, 6, 7, 7, 9]])

In [ ]:
X[0,:] # selecting a row

In [ ]:
print(X)

In [ ]:
X[:,1].argsort()  # the argsort for the column index 1

In [ ]:
print(X[ X[:,1].argsort() , : ])  # 'subset' X by the argsort to arrange X by the column